export { ChatInterface } from "./components/interface/chat-interface";
export { ChatGuard } from "./components/interface/chat-guard";
export { ConversationList } from "./components/sidebar/conversation-list";
export { ChatHeader } from "./components/header/chat-header";
export { KeyboardShortcutsDialog } from "./components/modals/keyboard-shortcuts-dialog";
export { ApiKeySection } from "./components/online-model-dialog/api-key-section";

export {
  useChatInput,
  useChatInputForm,
  useTextareaAutoResize,
  useDragDrop,
  useFileUpload,
  useSpeechToText,
  useChatMessages,
  useMessageStream,
  useSmartAutoScroll,
  useModels,
  useOnlineModels,
  useModelSelector,
  useModelSelectorDropdown,
  useConversationId,
  useConversationList,
  useConversationItem,
  useFolderItem,
  useChatGuard,
  useHeaderActions,
  useApiKeyManager,
  useCodeHighlighting,
  type UseChatInputFormProps,
  type UseChatInputFormReturn,
  type ModelDisplayInfo,
  type TranscriberStatus,
  type UseSpeechToTextResult,
  type UseChatMessagesProps,
  type UseChatMessagesReturn,
  type StreamResult,
  type UseSmartAutoScrollOptions,
  type UseSmartAutoScrollReturn,
  type UseOnlineModelsReturn,
  type UseModelSelectorReturn,
  type UseModelSelectorDropdownReturn,
  type FolderWithConversations,
  type UseConversationItemReturn,
  type UseFolderItemReturn,
  type UseApiKeyManagerReturn,
} from "./hooks";

export {
  findLastMessageByRole,
  truncateTitle,
  summarizeConversation,
  buildPrompt,
  formatAttachedFiles,
  buildMessageWithFiles,
  ERROR_MESSAGE_PREFIX,
  parseMessage,
  parseApiError,
  showErrorToast,
  processFile,
  validateFile,
  readFileContent,
  formatMessageTime,
  escapeHTML,
  generateHTML,
  generateMarkdown,
  downloadFile,
  getModelStatusKey,
  getStatusColor,
  getDisplayedStatus,
  getDisplayName,
  getTooltipText,
  getIconConfig,
  isSpeechButtonDisabled,
  isRecordingActive,
  STATUS_TOOLTIP,
  STATUS_ICON,
  getOnlineCategoryIcon,
  filterModelsByQuery,
  getLocalCategoryIcon,
  getCategoryLabel,
  getCategoryTooltip,
  getModelTypeIcon,
  getSpecializationIcon,
  getPerformanceBadgeVariant,
  type PromptMode,
  type ErrorActionType,
  type ParsedError,
  type ParseErrorOptions,
  type ValidateFileOptions,
  type ValidationResult,
  type ModelStatusKey,
  type ModelStatusFlags,
  type IconType,
  type IconConfig,
  type OnlineModelCategory,
  type LocalModelCategory,
  type ModelType,
  type Specialization,
  type PerformanceLevel,
} from "./utils";

export {
  createOpenRouterClient,
  getCategoryFromModel,
  transcribe,
  disposeTranscriber,
  type OpenRouterMessage,
  type StreamResponse,
  type OpenRouterModel,
  type OpenRouterClient,
  type ModelInfo,
  type ProgressInfo,
  type TranscribeOptions,
  type TranscribeResult,
  type WorkerMessage,
  type WorkerResponse,
} from "./lib";
